collections:
  authors:
    output: true
  missions:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "missions"
    values:
      layout: "mission"
      
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
